use MinorBodies;
drop table if exists Bodies;
create table Bodies (
	rms real,
	Peri real,
	Tp real,
	NEO_flag integer,
	Epoch real,
	One_km_NEO_flag integer,
	Orbit_type varchar(255),
	Ref varchar(255),
	Node real,
	Other_desigs varchar(100),
	PHA_flag integer,
	One_opposition_object_flag integer,
	Name varchar(255),
	G real,
	Perturbers_2 varchar(255),
	H real,
	M real,
	Num_opps integer,
	Perturbers varchar(255),
	Critical_list_numbered_object_flag integer,
	Orbital_period real,
	U varchar(255),
	Num_obs integer,
	Arc_years varchar(255),
	Arc_length integer,
	a real,
	e real,
	Last_obs varchar(255),
	i real,
	Perihelion_dist real,
	Number varchar(255),
	n real,
	Semilatus_rectum real,
	Hex_flags varchar(255),
	Computer varchar(255),
	Synodic_period real,
	Aphelion_dist real,
	Principal_desig varchar(255),
	primary key (Principal_desig)
);
